### ISSUE TITLE
Support inline tags

### ISSUE THREAD

**Issue by vschroeter** [vschroeter/obsidian-virtual-linker#10]
but when i test tag ignore feature, it's not working

## Note
<img width="628" alt="image" src="https://github.com/vschroeter/obsidian-virtual-linker/assets/2189610/5da0da1e-2fc4-4a64-a5f9-c3d7734a3c21">

## Note with `linker-exclude` tag
<img width="566" alt="image" src="https://github.com/vschroeter/obsidian-virtual-linker/assets/2189610/da609f42-fc90-43c4-befc-0e48af5d377a">

## Virtual Linker Setting:
<img width="834" alt="image" src="https://github.com/vschroeter/obsidian-virtual-linker/assets/2189610/30a7be64-b136-445a-a812-287c6a4ba6ad">

_Originally posted by @lifesign in https://github.com/vschroeter/obsidian-virtual-linker/issues/8#issuecomment-2190416618_

**Comment by vschroeter** [comment]
Fixed in f4d3ecd.

@lifesign: You can test it now in [Release 1.3.3](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.3.3)

**Comment by lifesign** [comment]
work like a charm~
