### ISSUE TITLE
Request: Option to exclude links to the current note

### ISSUE THREAD

**Issue by jamescoats** [vschroeter/obsidian-virtual-linker#11]
Hi, would like to see an option for when you have a note open, there won't be any links on that page to itself. I think it's cleaner for me this way.

**Comment by ttodosi** [comment]
ya this plugin in awesome! great work. exclude folders would be great if possible
maybe modifier click, or right click option to remove link too

**Comment by vschroeter** [comment]
I've added an option to exclude the currently active file from being linked.
You can test it now in [Version 1.3.5]( https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.3.5).

However, this suppression applies to **all visible** notes (if multiple tabs are open), not just the currently active note.
I have not yet found a way to restrict this to the respective editors only.

**Comment by vschroeter** [comment]
I've found a way (at least for most cases).
In [Version 1.3.6](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.3.6), it should not only exclude links to the active view (and thus also toggle visible links always, if you change the focus to another window) but links to the note itself.

**Comment by vschroeter** [comment]
Look at #21 for problems and updates regarding this issue.
