### ISSUE TITLE
Can you turn the console.log()'s off?

### ISSUE THREAD

**Issue by LynetteCullens** [vschroeter/obsidian-virtual-linker#13]
[obsidian.md-1720419163957.log](https://github.com/user-attachments/files/16123428/obsidian.md-1720419163957.log)

**Comment by vschroeter** [comment]
Done in [Version 1.3.5]( https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.3.5)

**Comment by LynetteCullens** [comment]
> Done in [Version 1.3.5](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.3.5)

Thank you. You're the only reason my brain works in a straight line. I appreciate your work. I can't find your "buy me a coffee" link, though. Does it exist?

**Comment by vschroeter** [comment]
Well, it exists now at the repo main page! Huge thanks for the support and the kind words, I'm glad you find the project useful!
