### ISSUE TITLE
Multiple links in same note

### ISSUE THREAD

**Issue by pkej** [vschroeter/obsidian-virtual-linker#15]
I'm experimenting with using this in my vault and I noticed that there are a couple of issues which are visible in the attached screen shot. As you can see if I use the same word several times "virtual linker" will render every instance as a link. This gets very "busy". In Wikipedia, and many other websites, the norm is to just link the first time, to let the reader be able to follow the link and learn, but not clutter every instance with the link.

Notice that I used the excellent feature from #6 at the beginning of the file. Kudos for using the link alias function of links to preserve the exact usage at that point in the document.

I suggest a toggle for us that prefer "render only first match of a link" (which should also be triggered by real links, e.g. my example)

<img width="318" alt="Screenshot 2024-07-11 at 00 31 33" src="https://github.com/vschroeter/obsidian-virtual-linker/assets/7883794/4873ecd7-d9f5-4e26-869c-511d0c96606e">

**Comment by vschroeter** [comment]
You're totally right, this can get very messy. The Wikipedia style of only linking the first occurence is just better in most cases.

I've added settings to toggle this behaviour, one for the suppression of multiple identical virtual links, one to suppress generation of virtual links if a real link to the same file exists.

This behaviour is activated now by default.

You can test it now in [Version 1.4.0](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.4.0) 

![image](https://github.com/vschroeter/obsidian-virtual-linker/assets/71217521/9748e9b4-7b12-49e9-aa7f-e408ca1ae9f0)

![image](https://github.com/vschroeter/obsidian-virtual-linker/assets/71217521/19b87111-efdf-403e-a8ba-8afd536ac1ed)

**Comment by vschroeter** [comment]
At the moment, however, this only works as expected for the edit mode. 
The reading mode rendering works differently in a more non-linear way, which makes it harder to suppress these multiple links. 
But I think the edit mode has priority anyway.

**Comment by pkej** [comment]
Wonderful. A fast toggle-command for turning Virtual linker on/off without having to go inside the settings would be nice.
