### ISSUE TITLE
Fast toggle-command for turning Virtual linker on/off

### ISSUE THREAD

**Issue by vschroeter** [vschroeter/obsidian-virtual-linker#17]
A fast toggle-command for turning Virtual linker on/off without having to go inside the settings would be nice. 

_Originally posted by @pkej in https://github.com/vschroeter/obsidian-virtual-linker/issues/15#issuecomment-2223907868_

**Comment by vschroeter** [comment]
Added a command to toggle the plugin in [Version 1.4.1](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.4.1).

You can set your own hot keys to that command :)

**Comment by pkej** [comment]
I will show it to my friend of 35 years. This will be the fruition of what we envisioned (together with a few other Obsidian plugins). 

Good there are people like you and the Obsidian team with the ability to execute and implement!
