### ISSUE TITLE
Freezing After Plugin Installation

### ISSUE THREAD

**Issue by sakkir91** [vschroeter/obsidian-virtual-linker#20]
Hello. I have noticed that after installing the plugin, the program's interface freezes and there are delays after commands. This is especially noticeable when switching between notes, navigating internal links, moving between cells, or adding rows/columns in tables. When I disable the plugin, everything works smoothly. Is this an issue on my end or a characteristic of the plugin? Can this be optimized in some way, like creating a cache or something similar?

**Comment by vschroeter** [comment]
When switching between nodes, the internal cache is updated. 
For my vault with around 200 files this update is not noticable and everyhting works smoothely.

So, freezes and lags should not be a characteristic of the plugin ;-)
I've already implemented some stuff to improve performance and cache a few things. 
But there still might be some improvement.

Do you have a much larger vault or a not so powerful computer?

Does these lags also occur when you type text?

**Comment by sakkir91** [comment]
Thank you for the response. My database contains over 2000 notes. I recorded a short [demonstration video](https://www.youtube.com/watch?v=nMlAUKSB91s) with two examples of lagging; I hope it conveys the extent of the issue. When I disable the plugin, everything works smoothly, as it should.

**Comment by vschroeter** [comment]
I see the problem, that is unacceptable.
Give me some time to dig into this, this should be solvable

**Comment by vschroeter** [comment]
I've implemented some improvements to the caching. 
I cannot avoid an initial update of the cache (similar to the indexing obsidian is doing itself), but after that, it should now work a loot smoother.

I tested it with a vault of 10000 notes, everything was fine for me.

You can test it now with the newest [Version 1.4.2](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.4.2).

Let me know, how it works for you!

**Comment by vschroeter** [comment]
Happy to hear, that it's working!
