### ISSUE TITLE
Define glossary Source

### ISSUE THREAD

**Issue by badrobit** [vschroeter/obsidian-virtual-linker#22]
I would love to be able to set the same or subfolder where the glossary is originating from

**Comment by vschroeter** [comment]
If I understand you correctly, you are able to specify those exact folders for the glossary, when the option "Include all files" is disabled.

<img width="923" alt="image" src="https://github.com/user-attachments/assets/9e22e005-96b9-41a9-aac5-7112254b77ac">


You can add those folders also using the context menu:

<img width="326" alt="image" src="https://github.com/user-attachments/assets/30d23f5c-b48b-47a0-b639-759ba76fd054">

**Comment by badrobit** [comment]
my bad I miss understood yes that does exactly what I was looking for.
