### ISSUE TITLE
Can it be made to provide suggestion of the filename while typing?

### ISSUE THREAD

**Issue by amatya-aditya** [vschroeter/obsidian-virtual-linker#24]
Can it suggest an existing filename to create a link if the few initial words match? This would help in cases where we might have forgotten the full filename in the vault, especially when there are many files over time. Providing suggestions, similar to how Google does, would allow us to link to already existing files more efficiently.

Thank you for the plugin.

**Comment by GevatterWolf** [comment]
You might want to have a look at the [Various Complements](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin) plugin for this.

**Comment by amatya-aditya** [comment]
Thanks, mate ❣️`
