### ISSUE TITLE
Folder inclusion/exclusion isn't working.

### ISSUE THREAD

**Issue by quelsemme** [vschroeter/obsidian-virtual-linker#26]
I chose to not have it run on all folders, and specified one specific folder, and it still runs on every note in my vault.

**Comment by vschroeter** [comment]
I think this was related to the recently introduced cache performance improvements and an issue that wasn't updating the cache on settings changes.
Should be fixed in [Version 1.4.4](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.4.4)

**Comment by vschroeter** [comment]
Ah, maybe I misunderstood the problem. So to clarify:
1) Is the problem, that the virtual linker is applied in every note? 
2) Or is the problem, that every note is included to be virtually linked, even if the note is not in '0001 Notes'?

If you say "it is showing up on all files" I think you mean problem 1), don't you?

The include/exclude options are meant for the files, that should be virtually linked in other notes. But the plugin itself is executed in every note of your vault, at the moment you cannot restrict it to work only in files of a specific folder.

**Comment by quelsemme** [comment]
Oh right, I've misunderstood then... I definitely thought the intention was whether to run it on all files or not... Because I have notes that don't need links... WIll take off the exclusion then :)

**Comment by Hypnophile** [comment]
Chiming in to say that this was very confusing for me too, and I would definitely love the ability to choose which directories are excluded (ie no files in that directory will contain virtual links) as well.
