### ISSUE TITLE
Add an option to exclude URLs from virtual link parsing

### ISSUE THREAD

**Issue by carlrobert** [vschroeter/obsidian-virtual-linker#29]
![image](https://github.com/user-attachments/assets/cd3c2683-504c-4bb8-9e30-0b9469854c82)

Parsing seems to cover URLs as well. Is there a way of disabling this?

**Comment by vschroeter** [comment]
Fixed in [Version 1.4.5](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.4.5).

**Comment by carlrobert** [comment]
Tested in Obsidian 1.6.7 on Linux. LGTM
