### ISSUE TITLE
Aliases get a superfluous .md extension

### ISSUE THREAD

**Issue by carlrobert** [vschroeter/obsidian-virtual-linker#35]
In my vault, the note "function" has "functions" as an alias. The "Convert to real link" feature acts differently on the alias.

In a new note, the first mention of "function" gets converted to `[[function]]`
whereas the first mention of "functions" gets converted to `[[function.md|functions]]`
with a redundant .md extension.

**Comment by vschroeter** [comment]
Do you want it rather to be converted to `[[function|functions]]`?

**Comment by carlrobert** [comment]
Yes, that makes most sense in my opinion. Or it can be an option in settings.

**Comment by vschroeter** [comment]
Fixed in [Version 1.4.7](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.4.7)

**Comment by carlrobert** [comment]
Tested in 1.4.7. LGTM
