### ISSUE TITLE
Don't propose links within backticks

### ISSUE THREAD

**Issue by carlrobert** [vschroeter/obsidian-virtual-linker#37]
If "pygame.md" exists as a note, then a backticked `pygame.init` is rendered as follows:
![image](https://github.com/user-attachments/assets/ae828d5b-215e-4175-8dd0-107e354b2bf4)

Now if you try to convert this to a real link via the context menu, you get a nonsensical result since links do not work within backticks: `[[pygame]].init`
![image](https://github.com/user-attachments/assets/6a043063-1186-40fa-930a-25782c4ee6be)

Furthermore, pygame is still offered up as a convertible link and converting once more to a real link yields
![image](https://github.com/user-attachments/assets/d8ef1d75-8735-4f93-8a21-19b00cc87bc0)

FWIW, within triple backticks the behaviour looks correct in that virtual links are not offered.
![image](https://github.com/user-attachments/assets/228a21d4-b2a0-4a82-8be0-3c76932e7adc)

**Comment by vschroeter** [comment]
Fixed in [Version 1.4.7](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.4.7)

**Comment by carlrobert** [comment]
Tested in 1.4.7. LGTM
