### ISSUE TITLE
Note references in bulleted items seem not to be taken into account 

### ISSUE THREAD

**Issue by carlrobert** [vschroeter/obsidian-virtual-linker#39]
Given input:
```
[[qubit]]
- qubit
- [[entropy]]
- entropy (2)
entropy (3)
```
qubit.md and entropy.md are pre-existing notes. Link once is enabled in the plugin.
FYI, the superscript values (41, 3) in the screenshots are reference counters from the Strange new worlds plugin. Disabling that plugin does not resolve the issue as far as I can see.

This renders as 
![image](https://github.com/user-attachments/assets/336b0b76-225b-480e-8e53-1b8fa3462b13)
I'd expect entropy (2) not to be a link candidate.

Converting entropy (2) to real link yields
![image](https://github.com/user-attachments/assets/cccd1968-9590-4899-b784-6072c313225c)
Now entropy (3) has become a link candidate, which is unexpected.

**Comment by vschroeter** [comment]
Should be fixed in [Version 1.4.8](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.4.8)

**Comment by carlrobert** [comment]
Verified in 1.4.8. LGTM. Thanks for your dedicated work!
