### ISSUE TITLE
Conflict with opening notes when plugin is active

### ISSUE THREAD

**Issue by websurfer93** [vschroeter/obsidian-virtual-linker#42]
I have been using this plugin for a few weeks, and it has been an excellent and useful tool. However, I have recently encountered an issue where, when the plugin is active, I am unable to open any of my notes. Whenever I try to open a note, I receive the error message "Failed to open """.

I discovered that the only way to resolve this issue is to deactivate the plugin, which allows me to open my notes again. This is quite frustrating, as I have become reliant on the plugin's functionality and do not want to discontinue using it.

I have tried clearing the Obsidian cache, but this only temporarily resolves the issue. The problem persists after subsequent uses of the plugin.

I would greatly appreciate if the developers could investigate this conflict and provide a solution to allow the plugin to be active while still enabling the opening of notes. This would ensure I can continue to benefit from the plugin's features without encountering this roadblock.
![image](https://github.com/user-attachments/assets/58ecbc1f-8bf3-47c7-91ca-1a827b111023)

**Comment by vschroeter** [comment]
Please check if it is fixed in [Version 1.4.9](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.4.9). 
If so, it should be the same problem with templated files as in #40.

**Comment by websurfer93** [comment]
Thank you for getting back to me so quickly. I cleared the cache and installed Version 1.4.9. So far, everything is functioning well. I appreciate your follow-up on this matter.

> Please check if it is fixed in [Version 1.4.9](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.4.9). If so, it should be the same problem with templated files as in #40.
