### ISSUE TITLE
Is There a Way to Make the Converted Links All Follow a Certain Link Format, Rather Than the Preset Format?

### ISSUE THREAD

**Issue by ProudBenzene** [vschroeter/obsidian-virtual-linker#46]
Hello, this plugin is so wonderful and it does link my notes together!

I am used to setting my default link format in the _Files&Links_ as _Relative path to file markdown link_, that's because I always embed photos into my notes and I want to make the photos visible in other md editors as Typora. Yet, I wish that related note markdown files should be linked through _the shortest path wiki link_. Since links converted with Virtual Linker are all markdown notes, I'd like to have an option that could specify the format of the converted links independently aside of the default setting in _Files&Links_ .

I hope you can consider my suggestions, and finally, thank you again for your developing such a cool plugin!🌷

**Comment by vschroeter** [comment]
There are now settings (when advanced settings are activated) to overwrite the default style for link conversion.
You can test it in [Version 1.5.0](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.5.0)
