### ISSUE TITLE
Some suggestions to "Match only whole words"

### ISSUE THREAD

**Issue by TempaYeshe** [vschroeter/obsidian-virtual-linker#47]
Hi,

Right now the settings "Match only whole words" does not work with some punctuations signs (`?`, `;`), i.e. they do not trigger a whole word. Also, some signs such as `-` are ambiguous as some people might want it to be a word end, others not. Therefore is it possible to have an option where we can set what we consider a punctuation sign (it would be filled by default with the current list, plus `?` and `;`)? Or at least add these two to the current list?  Or maybe there is a reason they are not there?

Another suggestion would be a "Match only start of words" setting, because in many languages you inflect the words with suffixes, so that "taking risks" would match the note "risk", but not "a brisk walk". 

Thank you

**Comment by vschroeter** [comment]
Thanks for the hint, I've just forgot to add some punctuations.
Now all punctuations are included by default. 
I've also added the `match also beginnings of words` setting and activated it by default, as this could be very useful.

You can test it not in [Version 1.5.0](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.5.0).

**Comment by TempaYeshe** [comment]
Thank you, works like a charm! Yet is there a reason why you are not using `\p{P}` and using ASCII ranges instead to find word boundaries? From my unexperimented point of view, that would benefit non latin languages, but also latin languages as some punctation like em dash `—`or ornate punctuation like `†` are not ASCII.

**Comment by vschroeter** [comment]
Thanks for the tip with ´\p{P}´, my knowledge of RegEx seems a bit outdated 😅
I will add it in the next versions!

**Comment by vschroeter** [comment]
Fixed in [Version 1.5.1](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.5.1)
