### ISSUE TITLE
Tags in the body that start with # will also show links, which can be very distracting.

### ISSUE THREAD

**Issue by HeiMaoJingZhangGiaoGe** [vschroeter/obsidian-virtual-linker#49]
Tags in the body that start with # will also show links, which can be very distracting.

**Comment by jiajiala** [comment]
![image](https://github.com/user-attachments/assets/f0471af4-f96b-4c25-8cdf-ef5976c4d5b4)
My tag is destroyed

**Comment by vschroeter** [comment]
Should be fixed in [Version 1.4.10](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.4.10)
