### ISSUE TITLE
support the Chinese

### ISSUE THREAD

**Issue by calmwaves111** [vschroeter/obsidian-virtual-linker#5]
Thanks for your work, I love this plugin, it solves a big problem
But I now have a few features,highlight potential links only if the filename is all in English. Can you add Chinese support?

**Comment by vschroeter** [comment]
You're right, unicode characters in general were not supported at all. 
Should be fixed with ac9e01d :)

You can test it with the new [Version 1.1.1](https://github.com/vschroeter/obsidian-glossary/releases/tag/1.1.1)

**Comment by calmwaves111** [comment]
thanks for your hard work，everything work well

**Comment by calmwaves111** [comment]
Unfortunately, it is still problematic in Chinese, which does not use Spaces. It may have something to do with word segmentation

![image](https://github.com/vschroeter/obsidian-virtual-linker/assets/56907077/7c073e12-04b3-438e-81b7-c9232204ab6b)

**Comment by vschroeter** [comment]
I have explicitly excluded the case where a part of a word creates a virtual link. I felt it would be unusual for a random sub-part of a word to suddenly get a link. 
However, I can see that this is a problem for languages without spaces.

I think I'll introduce a setting to choose between "match whole words only" and "match partial words".

**Comment by vschroeter** [comment]
Part word matching is implemented (cea3bcc47c7c42861acfe0869deda5e961064d09).

Furthermore, you can toggle the suffix rendering for part-words, so that the part of a word is not tear apart by the suffix (
ff7fc29).

![image](https://github.com/vschroeter/obsidian-virtual-linker/assets/71217521/66be6aad-f6fb-499c-9246-642f1ca87934)

**Comment by vschroeter** [comment]
You can test it now with [Release 1.2.2](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.2.2)

**Comment by calmwaves111** [comment]
Good. You've thought it through
