### ISSUE TITLE
Virtual links are kept the same color as normal text, with only a horizontal line underneath to keep reading smooth

### ISSUE THREAD

**Issue by jiajiala** [vschroeter/obsidian-virtual-linker#50]
This is the plugin I've been waiting for!

As in the image, virtual links are better distinguished from real links. Virtual links are usually almost the same as other text, except that they have a very shallow horizontal line at the bottom.
![5](https://github.com/user-attachments/assets/59e79b90-c1cb-4b9a-888c-c4fce2e762e1)
Just like this one, when unchecked there is a horizontal line at the bottom, which appears blue when the mouse moves over it

This is usually a weak reminder, and when the mouse moves to the above, it becomes a strong reminder

**Comment by jiajiala** [comment]
I can't find the css that separates it from the real link, I want it to be like any other normal text before I move my mouse over it, only there is a thin horizontal line at the bottom so it doesn't break the train of thought, and now the article is full of various virtual links, resulting in a lot of color in the text

**Comment by Salamander230** [comment]
Hello, fellow user of the plugin here!

Here is a css snippet that I've gotten to work which does what you describe, targeting only the virtual links. It should look pretty similar to the example you showed, but you can feel free to change the values to get the specific appearance that you want.

```
/* properties of the virtual link when not hovered */
.glossary-entry.virtual-link a {
    color: inherit;
    text-decoration-thickness: 1px;
    text-underline-offset: 0.23em;
    text-decoration-color: rgb(70, 100, 70, 0.33);
    text-decoration-style: solid;
}

/* properties of the virtual link when hovered */
.glossary-entry.virtual-link a:hover {
    color: rgb(70, 100, 70, 1);
    font-weight: 500;
    text-decoration-color: rgb(70, 100, 70, 1);
    text-decoration-style: solid;
}
```

Let me know if it works for you :)

**Comment by jiajiala** [comment]
@Salamander230 Thank you, this really helps me a lot, this should be seen by all users, thank you very much indeed

**Comment by vschroeter** [comment]
I've added it to the project's readme

**Comment by Salamander230** [comment]
@jiajiala Thank you! Happy to help :)

@vschroeter Thanks for adding it to the readme. The below works better for the readme because it has the correct style for all the comments (`/* */`), adds `!important` to all the `color` lines (for them to work both in reading & viewing mode), and has a few small changes/additions like `text-underline-position` and `text-decoration-style`.

Also, note that when the user targets `.glossary-entry.virtual-link` (or `.virtual-link.glossary-entry`), `!important` becomes unnecessary.

So, I believe either one of the following two code-blocks is better:

Using `.virtual-link`:
```
/* Properties of the virtual link when not hovered */
.virtual-link a {
    /* To have the normal text color when not hovered */
    color: inherit !important;

    /* Or add a color, e.g. red */
    /* color: red !important; */

    /* You can also change the underline of the link in thickness, color, and other properties */
    text-decoration-thickness: 1px;
    text-decoration-color: rgb(70, 100, 70, 0.33);
    text-underline-position: under;
    /* text-decoration-style: dotted; */
    /* text-underline-offset: 0em; */
}

/* Properties of the virtual link when hovered */
.virtual-link a:hover {
    color: rgb(70, 100, 70, 1) !important;
}
```

Using `.virtual-link.glossary-entry`:
```
/* Properties of the virtual link when not hovered */
.virtual-link.glossary-entry a {
    /* To have the normal text color when not hovered */
    color: inherit;

    /* Or add a color, e.g. red */
    /* color: red; */

    /* You can also change the underline of the link in thickness, color, and other properties */
    text-decoration-thickness: 1px;
    text-decoration-color: rgb(70, 100, 70, 0.33);
    text-underline-position: under;
    /* text-decoration-style: dotted; */
    /* text-underline-offset: 0em; */
}

/* Properties of the virtual link when hovered */
.virtual-link.glossary-entry a:hover {
    color: rgb(70, 100, 70, 1);
}
```

**Comment by vschroeter** [comment]
Thanks @Salamander230, I've added your example to the readme, they do look better ;-)

Actually, the `glossary-entry` class is a legacy class from earlier versions, but I like that this allows the `!important` to be ommited.

**Comment by Salamander230** [comment]
Thanks for the addition. Also looking forward to see how this plugin develops in the future :)
