### ISSUE TITLE
Conflicts With Obsidian Natural Outline

### ISSUE THREAD

**Issue by ProudBenzene** [vschroeter/obsidian-virtual-linker#51]
<img width="838" alt="image" src="https://github.com/user-attachments/assets/6deaf27c-c1fc-41ca-8e60-2ccd9d8f2022">

As the image shows, if there's a virtual link in a Heading, in the outline the word with virtual link would be missing. As a comparison, Heading with a virtual link could be displayed normally in the Quiet Outline Plugin.

This plugin is very powerful. Thank you for your dedication, and I hope this issue can be fixed soon!

**Comment by vschroeter** [comment]
I couldn't reproduce the problem with the quiet outline plugin. 
Can you try again with the newest version and if the problem persists, show me the settings of the plugin?

**Comment by ProudBenzene** [comment]
I'm sorry but it seems you misunderstand me. What I mean is that the display of headings is **normal** in the quiet outline plugin, but for **Obsidian's native outline**, the fields corresponding to headings with virtual links are **not** displayed.

Could you please reproduce it again?

**Comment by vschroeter** [comment]
For me, the normal obisidian outline also works fine.
Maybe there are some settings or interferences with other plugins, that cause the problem in the normal outline?

**Comment by ProudBenzene** [comment]
You're right, I found this normal in the default theme, too. I'll take this issue to the author of the Border Theme. 

THX!
