### ISSUE TITLE
[Feature Request] Allow case-sensitivity to be alias-specific

### ISSUE THREAD

**Issue by Salamander230** [vschroeter/obsidian-virtual-linker#52]
Thanks for a wonderful plugin! I was looking for something like this for a while and I can't believe it's not a core plugin in obsidian. Thank you so much :)

I think it would be awesome if we can allow specific aliases in the same file to be case-sensitive and others not. I know case-sensitivity was addressed in other issues (#3 and #9), but that only allows control of case-sensitivity on global and per file scales, not a per alias one.

### 1. Locally, using a frontmatter field

For example, we can have a `match-case` field that lists the specific aliases/filename in a file that need to be case-sensitive.
```
---
aliases:
  - RNA
  - Ribonucleic acid
match-case:
  - RNA
---
```

#### For example, if a user sets a threshold of 50% capital letters, this would be the result:

**Case-sensitive aliases (> 50% capital letters):**
- "WHO": 100% capital letters
- "C-13": 100% capital letters
- "mRNA": 75% capital letters
- "IFN-α": 75% capital letters

**Case-ambiguous aliases (= 50% capital letters; user decides case-sensitivity via a toggle):**
- "As"
- "If"
- "5' RNA cap"

**Case-insensitive aliases (< 50% capital letters):**
- "Anonymous"
- "WHO organization"
- "Transfer RNA"

If implementing one or both approaches is doable, that would be a wonderful addition to the plugin, especially the first approach since it's more granular.

Thanks for all of your hard work :)

**Comment by Salamander230** [comment]
Also, perhaps allowing another `ignore-case` field would be good too. The user can use either, neither, or both the `match-case` and `ignore-case` fields depending on their need to specify. For the aliases that aren't listed in either field, the file/global settings will prevail.
```
---
aliases:
  - RNA capping
  - RNA 5' cap
ignore-case:
  - RNA 5' cap
---
```

**Comment by vschroeter** [comment]
Thanks for the suggestions! 
I've added both in [Version 1.4.10](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.4.10):
- you can now specifiy for each alias (and the document name) if it should be case matched or ignored by adding it to the frontmatter list `linker-match-case` or `linker-ignore-case`
- words with mainly upper case letters are automatically case matched unless you specify that they shouldn't

**Comment by Salamander230** [comment]
Thanks for the quick update! I really appreciate it :) Just tested it out on my vault and it's working perfectly.

**Comment by vschroeter** [comment]
In [Version 1.5.0](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.5.0) there are now also advanced setting to control the property names and the capital letter percentage.
