### ISSUE TITLE
Add right click menu to convert to real link

### ISSUE THREAD

**Issue by calmwaves111** [vschroeter/obsidian-virtual-linker#6]
This plugin helped me a lot because I could find potential links while browsing the body text without having to open the outgoinglinks panel

Now I have a new FR to add a way to convert some of these links to real links
For example, adding options to the right-click menu. (It could be another implementation, but this is the only one I have in mind for now

by the way, I'm not sure if you know another note-taking software [siyuan](https://github.com/siyuan-note/siyuan), I really like siyuan's **virtual reference**, but there is no plugin to implement it in obsidian. Finally I found your plugin and it basically met my needs. Thanks again for your work.

**Comment by vschroeter** [comment]
I'm glad you find this plugin useful! :)

The converion of the links within a context menu is a good idea, I've added it in 9d84d896311d4172a507b92412db857ed3025f63.
In this context I also renamed the plugin to `virtual-linker` as it is meanwhile more than just for a glossary.

You can test it now in [Release 1.2.0](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.2.0)

**Comment by calmwaves111** [comment]
everything work well
