### ISSUE TITLE
Match also end of words

### ISSUE THREAD

**Issue by Kristof-h** [vschroeter/obsidian-virtual-linker#60]
First, thanks for this great module that really changed my way of linking notes.

Here is my issue : 
In French, a lot of words can have prefixes depending the way you use them.
For exemple the word « insecte » can easily be written « l’insecte ». In that case it will not be detected by Virtual Linker.
So I was wondering if a « Match also end of words »features could solve all those cases.

Thanks in advance.

**Comment by vschroeter** [comment]
Good point, I added this as setting in [Version 1.5.1](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.5.1) and enabled it by default.
