### ISSUE TITLE
[Feedback] The menu item's text is too long

### ISSUE THREAD

**Issue by Moyf** [vschroeter/obsidian-virtual-linker#69]
![image](https://github.com/user-attachments/assets/709c75d5-6831-4c40-aea8-07658e20fcb2)

It will make the whole right-button menu sooooo width, could you please consider shorten it?

**Comment by jiajiala** [comment]
I had the same problem

**Comment by vschroeter** [comment]
Fixed in [1.5.1](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.5.1)
