### ISSUE TITLE
Compatible with the MD-link format

### ISSUE THREAD

**Issue by calmwaves111** [vschroeter/obsidian-virtual-linker#7]
I did this in the Settings page
![image](https://github.com/vschroeter/obsidian-virtual-linker/assets/56907077/233f83b9-6293-43af-a2e1-13ae0ec73d12)

For a hardcoded links that is not in wiki format, it is still recognized as a virtual link
![image](https://github.com/vschroeter/obsidian-virtual-linker/assets/56907077/110c2e57-c663-4e70-8e81-3fd63c708dc5)

**Comment by calmwaves111** [comment]
https://github.com/vschroeter/obsidian-virtual-linker/issues/6
It would be even better if the converted format could also follow the obsidian setting

**Comment by vschroeter** [comment]
Should be fixed in 70c6652 and ebf248f.
You can test it in [Release 1.2.1](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.2.1)

**Comment by calmwaves111** [comment]
work well
