### ISSUE TITLE
add an option to exclude the suggestion of heading tags

### ISSUE THREAD

**Issue by lifesign** [vschroeter/obsidian-virtual-linker#8]
When I open my dailynote, I found that the text in the heading section is also being added as virtual links, which is not the expected result. Can we exclude the suggestion of heading text?

**Comment by vschroeter** [comment]
Of course, we can do that.
Could you provide me with an example or screenshot so that I can better understand your case?

**Comment by lifesign** [comment]
1. create a note named "work plan"
<img width="859" alt="image" src="https://github.com/vschroeter/obsidian-virtual-linker/assets/2189610/2a33e7e4-cd1b-4519-a44c-b819f4fb2fbf">


2. the h2 heading became a virtual link
<img width="826" alt="image" src="https://github.com/vschroeter/obsidian-virtual-linker/assets/2189610/817a18a0-2aaf-421f-85ee-9a9add42d1d3">

**Comment by vschroeter** [comment]
I've added a setting to toggle the matching of headers globally.

You can test it now in [Release 1.3.1](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.3.1)

**Comment by lifesign** [comment]
the heading part is ok now. but seems another issue.

i don't know why the space became a virtual link

<img width="808" alt="image" src="https://github.com/vschroeter/obsidian-virtual-linker/assets/2189610/90738fd4-8042-46a2-bb1f-1922bad1ba00">

**Comment by vschroeter** [comment]
Hmm, that's weird, I also cannot reproduce it.
If have added a little fix in [Release 1.3.2](https://github.com/vschroeter/obsidian-virtual-linker/releases/tag/1.3.2) that maybe could fix this. 

However, since I have not been able to reproduce the problem, it is also possible that it is not working.
After installing 1.3.2, can you please reload obsidian, reopen your vault and your note? 
If it's not working, can you attach the test note and a screenshot of your settings please?

**Comment by lifesign** [comment]
yep, the issue was fixed~

**Comment by lifesign** [comment]
but when i test tag ignore feature, it's not working

<img width="628" alt="image" src="https://github.com/vschroeter/obsidian-virtual-linker/assets/2189610/5da0da1e-2fc4-4a64-a5f9-c3d7734a3c21">

**Comment by vschroeter** [comment]
Indeed, I had only implemented support for [frontmatter tags](https://notes.nicolevanderhoeven.com/obsidian-playbook/Obsidian+Plugins/Core+Plugins/Tags#Tagging+notes).
See #10 for updates
